AWSTemplateFormatVersion: "2010-09-09"
Description: "Xxxxxx Security Groups services stack"

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'SSH Access CIDR`s'
      Parameters:
      # - deleted a lot
      - UfaIP

Parameters:
  UfaIP:
    Type: "String"
    MinLength: "9"
    MaxLength: "18"
    Default: "x/32"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "must be a valid CIDR range of the form x.x.x.x/x."
  VPC:
    Description: "A VPC ID."
    Type: "String"
  VPCcidr:
    Description: "A VPC Network CIDR"
    Type: "String"
  DefaultSecurityGroup:
    Description: "Xxxxxx VPC Default Security Group"
    Type: "String"

Resources:
  DefaultInboundRule:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      IpProtocol: "-1"
      CidrIp: "127.0.0.1/32"
      GroupId: !Ref DefaultSecurityGroup
  DefaultOutboundRule:
    Type: "AWS::EC2::SecurityGroupEgress"
    Properties:
      IpProtocol: "-1"
      CidrIp: "127.0.0.1/32"
      GroupId: !Ref DefaultSecurityGroup
  MailOutSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Xxxxxx Main Outbound to Mail Relay servers security group"
      VpcId: !Ref "VPC"
      SecurityGroupEgress:
      - IpProtocol: "tcp"
        FromPort: "25"
        ToPort: "25"
        CidrIp: "x/32"
      - IpProtocol: "tcp"
        FromPort: "25"
        ToPort: "25"
        CidrIp: "x/32"
      # - deleted a lot
      Tags:
      - Key: "Name"
        Value: "MailOutSG"
  EFSforHOMESecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref "VPC"
      Tags:
      - Key: "Name"
        Value: "EFSforHOMESecurityGroup"
      GroupDescription: "EFS for HOME directories Security group"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 2049
        ToPort: 2049
        SourceSecurityGroupId: !Ref BastionSecurityGroup
      - IpProtocol: tcp
        FromPort: 2049
        ToPort: 2049
        SourceSecurityGroupId: !Ref NFSDevServicesSecurityGroup
      # - deleted a lot
  BastionSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    DependsOn:
      - Xxxxxx
    Properties:
      GroupDescription: "Enable access to the Bastion host"
      VpcId: !Ref "VPC"
      Tags:
      - Key: "Name"
        Value: "BastionSecurityGroup"
      SecurityGroupIngress:
      - IpProtocol: "tcp"
        FromPort: "22"
        ToPort: "22"
        SourceSecurityGroupId: !Ref Xxxxxx
        Description: Remote Access VPN users
      # - deleted a lot
      SecurityGroupEgress:
      - IpProtocol: "-1"
        FromPort: "0"
        ToPort: "65535"
        CidrIp: !Ref VPCcidr
      # - deleted a lot
  
  # Mass deleted


Outputs:
  SecurityGroupsStackName:
    Description: "Security Groups Stack Name"
    Value: !Ref "AWS::StackName"

  # Mass deleted 
