AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS stack"

Parameters:
  VPCId:
    Description: "A VPC ID."
    Type: "String"
  InstanceClass:
    Description: "The database instance type"
    Type: "String"
    AllowedValues:
    - db.t3.small
    - db.r5.large
    - db.r5.xlarge
    - db.r5.2xlarge
    ConstraintDescription: "Must select a valid database instance type."
  BackupRetention:
    Description: "Number of days to keep backup for MySQL"
    Type: "Number"
    MinValue: "0"
    MaxValue: "7"
    Default: "1"
    ConstraintDescription: "Must be between 0 and 7"
  MasterUserPassword:
    NoEcho: "true"
    Description: "The database admin account password"
    Type: "String"
    MinLength: "8"
    MaxLength: "41"
    ConstraintDescription: "Must contain only alphanumeric characters."
  MasterUsername:
    Description: "The RDS MySQL database admin account username"
    Type: "String"
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "Must begin with a letter and contain only alphanumeric characters."
  Subnet1:
    Description: "A private VPC subnet ID in AZ1."
    Type: "String"
  Subnet2:
    Description: "A private VPC subnet ID in AZ2."
    Type: "String"
  SecurityGroup:
    Description: "MySQL Security Group"
    Type: "String"
  OperatorEMail:
    Description: 'Xxxxxx Services EMail address'
    Type: String
    AllowedPattern: "([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)"
    ConstraintDescription: 'must be a valid email address.'
  Enabled:
    Description: '"Enabled" to create database instances, "Disabled" to remove them while leaving Cluster Group intact'
    Type: String
    AllowedValues:
      - Enabled
      - Disabled
    Default: Enabled

Conditions:
  IsEnabled: !Equals [ !Ref Enabled, Enabled ]

Resources:
  SubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "MySQL Subnet Group"
      SubnetIds:
      - !Ref "Subnet1"
      - !Ref "Subnet2"

  SNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
      - Endpoint: !Ref OperatorEMail
        Protocol: email

  AuroraClusterParamGroup:
    Type: 'AWS::RDS::DBClusterParameterGroup'
    Properties:
      Description: "Cluster parameter group"
      Family: aurora-mysql5.7
      Parameters:
        innodb_file_per_table: "0"
        innodb_purge_threads: "1"
        binlog_format: "MIXED"

  AuroraParamGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Family: aurora-mysql5.7
      Description: "Parameter group"
      Parameters:
        ft_min_word_len: "3"
        # mass deleted

  AuroraCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      BackupRetentionPeriod: !Ref BackupRetention
      DBClusterParameterGroupName: !Ref AuroraClusterParamGroup
      DBSubnetGroupName: !Ref SubnetGroup
      DeletionProtection: true
      Engine: aurora-mysql
      EngineVersion: 5.7.mysql_aurora.2.07.1
      KmsKeyId: !GetAtt KMSKey.Arn
      MasterUsername: Xxxxxx
      MasterUserPassword: !Ref MasterUserPassword
      StorageEncrypted: true
      VpcSecurityGroupIds:
      - !Ref SecurityGroup

  AuroraInstance1:
    Type: AWS::RDS::DBInstance
    Condition: IsEnabled
    Properties:
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: !Ref InstanceClass
      DBParameterGroupName: !Ref AuroraParamGroup
      Engine: aurora-mysql

  AuroraInstance2:
    Type: AWS::RDS::DBInstance
    Condition: IsEnabled
    Properties:
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: !Ref InstanceClass
      DBParameterGroupName: !Ref AuroraParamGroup
      Engine: aurora-mysql

  Instance1CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsEnabled
    DependsOn:
      - AuroraInstance1
      - SNSTopic
    Properties:
      AlarmDescription: "Database CPU utilization is over 80%."
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Unit: Percent
      Statistic: Average
      Period: 60
      EvaluationPeriods: 15
      Threshold: 80
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref AuroraInstance1
      AlarmActions:
      - Ref: SNSTopic
      InsufficientDataActions:
      - Ref: SNSTopic

  Instance2CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsEnabled
    DependsOn:
      - AuroraInstance2
      - SNSTopic
    Properties:
      AlarmDescription: "Database CPU utilization is over 80%."
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Unit: Percent
      Statistic: Average
      Period: 60
      EvaluationPeriods: 15
      Threshold: 80
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref AuroraInstance2
      AlarmActions:
      - Ref: SNSTopic
      InsufficientDataActions:
      - Ref: SNSTopic

  KMSKey:
    DeletionPolicy: Retain
    Type: 'AWS::KMS::Key'
    Properties:
      Description: 'Aurora KMS Key'
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
          Action: 'kms:*'
          Resource: '*'
        - Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - 'kms:Encrypt'
          - 'kms:Decrypt'
          - 'kms:ReEncrypt*'
          - 'kms:GenerateDataKey*'
          - 'kms:CreateGrant'
          - 'kms:ListGrants'
          - 'kms:DescribeKey'
          Resource: '*'
          Condition:
            StringEquals:
              'kms:CallerAccount': !Ref 'AWS::AccountId'
              'kms:ViaService': !Sub 'rds.${AWS::Region}.amazonaws.com'

  KMSKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: !Sub 'alias/${AWS::StackName}'
      TargetKeyId: !Ref KMSKey

Outputs:
  AuroraEndpoint:
    Description: "The connection endpoint for the Xxxxxx RDS MySQL Aurora database"
    Value: !GetAtt AuroraCluster.Endpoint.Address
